version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build-zm:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Check Style
          command: yarn run prettier --check .
      - run:
          name: Test Functions
          command: yarn workspace @zm-blood-components/functions test

workflows:
  blood-components:
    jobs:
      - build-zm
