name: App Production Deployment

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Choose 'coordinator' or 'donor'"
        required: true
      version:
        description: "Version to deploy"
        required: true

jobs:
  donor_hosting_qa:
    name: ${{ github.event.inputs.app }} production deployment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.app == 'coordinator' || github.event.inputs.app == 'donor' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.version }}

      - name: Set Envitonment Variable to Production
        run: echo "REACT_APP_PRODUCTION_FIREBASE=true" >> "$GITHUB_ENV"

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Set tag before build
        run: echo "REACT_APP_VERSION=${{steps.tag.outputs.tag}}" >> "$GITHUB_ENV"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Common
        run: yarn workspace @zm-blood-components/common build

      - name: Build ${{ github.event.inputs.app }}
        run: yarn workspace @zm-blood-components/${{ github.event.inputs.app }} build

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:${{ github.event.inputs.app }} -P production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
