name: Donor Production Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Donor commit to deploy"
        required: false

jobs:
  donor_hosting_qa:
    name: Donor Production Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install
      - name: Set Envitonment Variable to Production
        run: echo "REACT_APP_PRODUCTION_FIREBASE=true" >> "$GITHUB_ENV"
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:donor -P production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
